services:
  user_conn_data_db:
    image: redis:7
    container_name: user_conn_data_db
    ports:
      - "${USER_CONN_DATA_DB_PORT:-6379}:6379"
    volumes:
      - "./redis/redis.conf:/usr/local/etc/redis/redis.conf:ro"
      - "./.docker_volumes/redis_data:/data"
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
